using System.Collections.Immutable;
using System.Text;

namespace TurboMediator.SourceGenerator;

/// <summary>
/// Generates the Mediator implementation and DI registration code.
/// </summary>
internal static class Emitter
{
    public static string GenerateMediatorImplementation(
        ImmutableArray<HandlerInfo> handlers,
        ImmutableArray<MessageInfo> messages,
        string namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using TurboMediator;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // Generate Mediator class
        GenerateMediatorClass(sb, handlers);

        // Generate extension methods
        GenerateExtensionMethods(sb, handlers, messages, namespaceName);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateMediatorClass(StringBuilder sb, ImmutableArray<HandlerInfo> handlers)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Generated Mediator implementation with pipeline support.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class Mediator : IMediator");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine("        private readonly TurboMediatorOptions _options;");
        sb.AppendLine();
        sb.AppendLine("        public Mediator(IServiceProvider serviceProvider, IOptions<TurboMediatorOptions>? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("            _options = options?.Value ?? new TurboMediatorOptions();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate Send methods for requests
        GenerateSendMethods(sb, handlers);

        // Generate Publish method for notifications
        GeneratePublishMethod(sb, handlers);

        // Generate CreateStream methods
        GenerateStreamMethods(sb, handlers);

        // Generate pipeline helper method
        GeneratePipelineHelper(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GeneratePipelineHelper(StringBuilder sb)
    {
        sb.AppendLine("        private async ValueTask<TResponse> ExecuteWithPipeline<TMessage, TResponse>(");
        sb.AppendLine("            TMessage message,");
        sb.AppendLine("            MessageHandlerDelegate<TResponse> handler,");
        sb.AppendLine("            CancellationToken cancellationToken)");
        sb.AppendLine("            where TMessage : IMessage");
        sb.AppendLine("        {");
        sb.AppendLine("            // Get pre-processors");
        sb.AppendLine("            var preProcessors = _serviceProvider.GetServices<IMessagePreProcessor<TMessage>>();");
        sb.AppendLine("            foreach (var preProcessor in preProcessors)");
        sb.AppendLine("            {");
        sb.AppendLine("                await preProcessor.Process(message, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Get pipeline behaviors");
        sb.AppendLine("            var behaviors = _serviceProvider.GetServices<IPipelineBehavior<TMessage, TResponse>>().ToArray();");
        sb.AppendLine();
        sb.AppendLine("            // Build the pipeline");
        sb.AppendLine("            MessageHandlerDelegate<TResponse> next = handler;");
        sb.AppendLine();
        sb.AppendLine("            for (int i = behaviors.Length - 1; i >= 0; i--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var behavior = behaviors[i];");
        sb.AppendLine("                var currentNext = next;");
        sb.AppendLine("                next = () => behavior.Handle(message, currentNext, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            TResponse response;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                response = await next();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                // Try exception handlers");
        sb.AppendLine("                var exceptionHandlers = _serviceProvider.GetServices<IMessageExceptionHandler<TMessage, TResponse, Exception>>();");
        sb.AppendLine("                foreach (var exHandler in exceptionHandlers)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var result = await exHandler.Handle(message, ex, cancellationToken);");
        sb.AppendLine("                    if (result.Handled)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        return result.Response!;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Get post-processors");
        sb.AppendLine("            var postProcessors = _serviceProvider.GetServices<IMessagePostProcessor<TMessage, TResponse>>();");
        sb.AppendLine("            foreach (var postProcessor in postProcessors)");
        sb.AppendLine("            {");
        sb.AppendLine("                await postProcessor.Process(message, response, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return response;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateSendMethods(StringBuilder sb, ImmutableArray<HandlerInfo> handlers)
    {
        var requestHandlers = handlers.Where(h => h.Kind == HandlerKind.Request && !h.IsStreaming).ToList();
        var commandHandlers = handlers.Where(h => h.Kind == HandlerKind.Command && !h.IsStreaming).ToList();
        var queryHandlers = handlers.Where(h => h.Kind == HandlerKind.Query && !h.IsStreaming).ToList();

        // Generic Send for IRequest<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public async ValueTask<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        foreach (var handler in requestHandlers)
        {
            var responseType = handler.ResponseTypeFullName ?? "Unit";
            var handlerType = handler.ResponseTypeFullName != null
                ? $"IRequestHandler<{handler.MessageTypeFullName}, {responseType}>"
                : $"IRequestHandler<{handler.MessageTypeFullName}>";
            sb.AppendLine($"                {handler.MessageTypeFullName} msg => (TResponse)(object)(await ExecuteWithPipeline<{handler.MessageTypeFullName}, {responseType}>(msg, () => _serviceProvider.GetRequiredService<{handlerType}>().Handle(msg, cancellationToken), cancellationToken)),");
        }

        sb.AppendLine("                _ => throw new InvalidOperationException($\"No handler registered for {request.GetType().Name}\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generic Send for ICommand<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public async ValueTask<TResponse> Send<TResponse>(ICommand<TResponse> command, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return command switch");
        sb.AppendLine("            {");

        foreach (var handler in commandHandlers)
        {
            var responseType = handler.ResponseTypeFullName ?? "Unit";
            var handlerType = handler.ResponseTypeFullName != null
                ? $"ICommandHandler<{handler.MessageTypeFullName}, {responseType}>"
                : $"ICommandHandler<{handler.MessageTypeFullName}>";
            sb.AppendLine($"                {handler.MessageTypeFullName} msg => (TResponse)(object)(await ExecuteWithPipeline<{handler.MessageTypeFullName}, {responseType}>(msg, () => _serviceProvider.GetRequiredService<{handlerType}>().Handle(msg, cancellationToken), cancellationToken)),");
        }

        sb.AppendLine("                _ => throw new InvalidOperationException($\"No handler registered for {command.GetType().Name}\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generic Send for IQuery<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public async ValueTask<TResponse> Send<TResponse>(IQuery<TResponse> query, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return query switch");
        sb.AppendLine("            {");

        foreach (var handler in queryHandlers)
        {
            var responseType = handler.ResponseTypeFullName!;
            sb.AppendLine($"                {handler.MessageTypeFullName} msg => (TResponse)(object)(await ExecuteWithPipeline<{handler.MessageTypeFullName}, {responseType}>(msg, () => _serviceProvider.GetRequiredService<IQueryHandler<{handler.MessageTypeFullName}, {responseType}>>().Handle(msg, cancellationToken), cancellationToken))!,");
        }

        sb.AppendLine("                _ => throw new InvalidOperationException($\"No handler registered for {query.GetType().Name}\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GeneratePublishMethod(StringBuilder sb, ImmutableArray<HandlerInfo> handlers)
    {
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public async ValueTask Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TNotification : INotification");
        sb.AppendLine("        {");
        sb.AppendLine("            var handlers = _serviceProvider.GetServices<INotificationHandler<TNotification>>();");
        sb.AppendLine("            if (_options.ThrowOnNoNotificationHandler && !handlers.Any())");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new InvalidOperationException($\"No notification handler registered for {typeof(TNotification).Name}\");");
        sb.AppendLine("            }");
        sb.AppendLine("            await _options.NotificationPublisher.Publish(handlers, notification, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateStreamMethods(StringBuilder sb, ImmutableArray<HandlerInfo> handlers)
    {
        var streamRequestHandlers = handlers.Where(h => h.Kind == HandlerKind.Request && h.IsStreaming).ToList();
        var streamCommandHandlers = handlers.Where(h => h.Kind == HandlerKind.Command && h.IsStreaming).ToList();
        var streamQueryHandlers = handlers.Where(h => h.Kind == HandlerKind.Query && h.IsStreaming).ToList();

        // Stream for IStreamRequest<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");

        if (streamRequestHandlers.Any())
        {
            sb.AppendLine("            return request switch");
            sb.AppendLine("            {");
            foreach (var handler in streamRequestHandlers)
            {
                sb.AppendLine($"                {handler.MessageTypeFullName} msg => ExecuteStreamWithPipeline<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}, TResponse>(msg, () => _serviceProvider.GetRequiredService<IStreamRequestHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>>().Handle(msg, cancellationToken), cancellationToken),");
            }
            sb.AppendLine("                _ => throw new InvalidOperationException($\"No stream handler registered for {request.GetType().Name}\")");
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine("            throw new InvalidOperationException($\"No stream handler registered for {request.GetType().Name}\");");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Stream for IStreamCommand<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamCommand<TResponse> command, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");

        if (streamCommandHandlers.Any())
        {
            sb.AppendLine("            return command switch");
            sb.AppendLine("            {");
            foreach (var handler in streamCommandHandlers)
            {
                sb.AppendLine($"                {handler.MessageTypeFullName} msg => ExecuteStreamWithPipeline<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}, TResponse>(msg, () => _serviceProvider.GetRequiredService<IStreamCommandHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>>().Handle(msg, cancellationToken), cancellationToken),");
            }
            sb.AppendLine("                _ => throw new InvalidOperationException($\"No stream handler registered for {command.GetType().Name}\")");
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine("            throw new InvalidOperationException($\"No stream handler registered for {command.GetType().Name}\");");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Stream for IStreamQuery<TResponse>
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamQuery<TResponse> query, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");

        if (streamQueryHandlers.Any())
        {
            sb.AppendLine("            return query switch");
            sb.AppendLine("            {");
            foreach (var handler in streamQueryHandlers)
            {
                sb.AppendLine($"                {handler.MessageTypeFullName} msg => ExecuteStreamWithPipeline<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}, TResponse>(msg, () => _serviceProvider.GetRequiredService<IStreamQueryHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>>().Handle(msg, cancellationToken), cancellationToken),");
            }
            sb.AppendLine("                _ => throw new InvalidOperationException($\"No stream handler registered for {query.GetType().Name}\")");
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine("            throw new InvalidOperationException($\"No stream handler registered for {query.GetType().Name}\");");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Stream pipeline helper method
        GenerateStreamPipelineHelper(sb);

        // Helper method for casting IAsyncEnumerable
        sb.AppendLine("        private static async IAsyncEnumerable<TTarget> CastAsyncEnumerable<TSource, TTarget>(IAsyncEnumerable<TSource> source, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken))");
        sb.AppendLine("            {");
        sb.AppendLine("                yield return (TTarget)(object)item!;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateStreamPipelineHelper(StringBuilder sb)
    {
        sb.AppendLine("        private async IAsyncEnumerable<TTarget> ExecuteStreamWithPipeline<TMessage, TResponse, TTarget>(");
        sb.AppendLine("            TMessage message,");
        sb.AppendLine("            StreamHandlerDelegate<TResponse> handler,");
        sb.AppendLine("            [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)");
        sb.AppendLine("            where TMessage : IStreamMessage");
        sb.AppendLine("        {");
        sb.AppendLine("            // Get pre-processors");
        sb.AppendLine("            var preProcessors = _serviceProvider.GetServices<IStreamPreProcessor<TMessage>>();");
        sb.AppendLine("            foreach (var preProcessor in preProcessors)");
        sb.AppendLine("            {");
        sb.AppendLine("                await preProcessor.Process(message, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Get pipeline behaviors");
        sb.AppendLine("            var behaviors = _serviceProvider.GetServices<IStreamPipelineBehavior<TMessage, TResponse>>().ToArray();");
        sb.AppendLine();
        sb.AppendLine("            // Build the pipeline");
        sb.AppendLine("            StreamHandlerDelegate<TResponse> next = handler;");
        sb.AppendLine();
        sb.AppendLine("            for (int i = behaviors.Length - 1; i >= 0; i--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var behavior = behaviors[i];");
        sb.AppendLine("                var currentNext = next;");
        sb.AppendLine("                next = () => behavior.Handle(message, currentNext, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Execute and get stream");
        sb.AppendLine("            var stream = next();");
        sb.AppendLine();
        sb.AppendLine("            // Get post-processors and wrap stream if any");
        sb.AppendLine("            var postProcessors = _serviceProvider.GetServices<IStreamPostProcessor<TMessage, TResponse>>().ToArray();");
        sb.AppendLine("            foreach (var postProcessor in postProcessors)");
        sb.AppendLine("            {");
        sb.AppendLine("                stream = postProcessor.Process(message, stream, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Yield items");
        sb.AppendLine("            await foreach (var item in stream.WithCancellation(cancellationToken))");
        sb.AppendLine("            {");
        sb.AppendLine("                yield return (TTarget)(object)item!;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateExtensionMethods(StringBuilder sb, ImmutableArray<HandlerInfo> handlers, ImmutableArray<MessageInfo> messages, string namespaceName)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extension methods for registering TurboMediator with DI.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class TurboMediatorServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds TurboMediator services to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <remarks>Default lifetime is Scoped. Pass <c>ServiceLifetime.Singleton</c> for stateless handlers that don't inject scoped services.</remarks>");
        sb.AppendLine("        public static IServiceCollection AddTurboMediator(this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            return AddTurboMediator(services, (Action<TurboMediatorOptions>)(_ => { }));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds TurboMediator services to the service collection with the specified lifetime.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddTurboMediator(this IServiceCollection services, ServiceLifetime lifetime)");
        sb.AppendLine("        {");
        sb.AppendLine("            return AddTurboMediator(services, (Action<TurboMediatorOptions>)(_ => { }), lifetime);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds TurboMediator services to the service collection with fluent builder configuration.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("        /// <param name=\"configure\">Action to configure the mediator using the fluent builder API.</param>");
        sb.AppendLine("        /// <param name=\"lifetime\">The service lifetime for the mediator and handlers. Default is Scoped.</param>");
        sb.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine("        /// <example>");
        sb.AppendLine("        /// <code>");
        sb.AppendLine("        /// services.AddTurboMediator(builder => builder");
        sb.AppendLine("        ///     .WithParallelNotifications()");
        sb.AppendLine("        ///     .WithRetry&lt;MyCommand, MyResult&gt;(maxRetries: 3)");
        sb.AppendLine("        ///     .WithCircuitBreaker&lt;MyCommand, MyResult&gt;(failureThreshold: 5)");
        sb.AppendLine("        ///     .WithTelemetry&lt;MyCommand, MyResult&gt;())");
        sb.AppendLine("        /// </code>");
        sb.AppendLine("        /// </example>");
        sb.AppendLine("        public static IServiceCollection AddTurboMediator(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            Action<TurboMediatorBuilder> configure,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("        {");
        sb.AppendLine("            var builder = new TurboMediatorBuilder(services);");
        sb.AppendLine("            configure(builder);");
        sb.AppendLine();
        sb.AppendLine("            // Apply builder options");
        sb.AppendLine("            services.Configure<TurboMediatorOptions>(opt =>");
        sb.AppendLine("            {");
        sb.AppendLine("                opt.NotificationPublisher = builder.Options.NotificationPublisher;");
        sb.AppendLine("                opt.ThrowOnNoNotificationHandler = builder.Options.ThrowOnNoNotificationHandler;");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            // Apply configuration actions from builder");
        sb.AppendLine("            foreach (var action in builder.ConfigurationActions)");
        sb.AppendLine("            {");
        sb.AppendLine("                action(services);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Register Mediator");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(IMediator), typeof(Mediator), lifetime));");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(ISender), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(IPublisher), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine();
        sb.AppendLine("            // Register handlers");

        foreach (var handler in handlers.Where(h => !h.IsAbstract))
        {
            var handlerInterface = GetHandlerInterface(handler);
            sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({handlerInterface}), typeof({handler.HandlerTypeFullName}), lifetime));");
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds TurboMediator services to the service collection with configuration.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddTurboMediator(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            Action<TurboMediatorOptions> configure,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Register options");
        sb.AppendLine("            services.Configure(configure);");
        sb.AppendLine();
        sb.AppendLine("            // Register Mediator");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(IMediator), typeof(Mediator), lifetime));");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(ISender), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine("            services.Add(new ServiceDescriptor(typeof(IPublisher), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine();
        sb.AppendLine("            // Register handlers");

        foreach (var handler in handlers.Where(h => !h.IsAbstract))
        {
            var handlerInterface = GetHandlerInterface(handler);
            sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({handlerInterface}), typeof({handler.HandlerTypeFullName}), lifetime));");
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a pipeline behavior to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddPipelineBehavior<TBehavior>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TBehavior : class");
        sb.AppendLine("        {");
        sb.AppendLine("            // Get all IPipelineBehavior<,> interfaces implemented by TBehavior");
        sb.AppendLine("            var behaviorType = typeof(TBehavior);");
        sb.AppendLine("            var pipelineInterfaces = behaviorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IPipelineBehavior<,>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in pipelineInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, behaviorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a pre-processor to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddPreProcessor<TProcessor>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TProcessor : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var processorType = typeof(TProcessor);");
        sb.AppendLine("            var preProcessorInterfaces = processorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMessagePreProcessor<>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in preProcessorInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, processorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a post-processor to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddPostProcessor<TProcessor>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TProcessor : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var processorType = typeof(TProcessor);");
        sb.AppendLine("            var postProcessorInterfaces = processorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMessagePostProcessor<,>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in postProcessorInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, processorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds an exception handler to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddExceptionHandler<THandler>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where THandler : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var handlerType = typeof(THandler);");
        sb.AppendLine("            var exceptionHandlerInterfaces = handlerType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMessageExceptionHandler<,,>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in exceptionHandlerInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, handlerType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a stream pipeline behavior to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddStreamPipelineBehavior<TBehavior>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TBehavior : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var behaviorType = typeof(TBehavior);");
        sb.AppendLine("            var streamBehaviorInterfaces = behaviorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IStreamPipelineBehavior<,>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in streamBehaviorInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, behaviorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a stream pre-processor to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddStreamPreProcessor<TProcessor>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TProcessor : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var processorType = typeof(TProcessor);");
        sb.AppendLine("            var preProcessorInterfaces = processorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IStreamPreProcessor<>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in preProcessorInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, processorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds a stream post-processor to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddStreamPostProcessor<TProcessor>(");
        sb.AppendLine("            this IServiceCollection services,");
        sb.AppendLine("            ServiceLifetime lifetime = ServiceLifetime.Singleton)");
        sb.AppendLine("            where TProcessor : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var processorType = typeof(TProcessor);");
        sb.AppendLine("            var postProcessorInterfaces = processorType.GetInterfaces()");
        sb.AppendLine("                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IStreamPostProcessor<,>));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var interfaceType in postProcessorInterfaces)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.Add(new ServiceDescriptor(interfaceType, processorType, lifetime));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");

        // Generate ConfigureFromAttributes method for zero-reflection attribute scanning
        GenerateConfigureFromAttributes(sb, messages);

        // Generate ConfigureRecurringJobsFromAttributes method for [RecurringJob] auto-registration
        GenerateConfigureRecurringJobs(sb, handlers);

        sb.AppendLine("    }");
    }

    private static void GenerateConfigureFromAttributes(StringBuilder sb, ImmutableArray<MessageInfo> messages)
    {
        // Filter messages that have at least one known attribute
        // For non-notification messages, a response type is required; notifications may have WithOutbox.
        var attributedMessages = messages.Where(m =>
            (m.HasTransactional || m.HasAuditable || m.HasRequiresTenant || m.HasAuthorize || m.HasWithOutbox) &&
            (m.ResponseTypeFullName != null || m.HasWithOutbox)
        ).ToList();

        if (attributedMessages.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Configures pipeline behaviors based on attributes detected at compile time.");
        sb.AppendLine("        /// This is a zero-reflection replacement for *FromAttributes methods.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// Detected attributes: [Transactional], [Auditable], [RequiresTenant], [Authorize], [WithOutbox].");
        sb.AppendLine("        /// Usage: services.AddTurboMediator(builder =&gt; builder.ConfigureFromAttributes());");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        public static TurboMediatorBuilder ConfigureFromAttributes(this TurboMediatorBuilder builder)");
        sb.AppendLine("        {");

        foreach (var msg in attributedMessages)
        {
            var responseType = msg.ResponseTypeFullName ?? "TurboMediator.Unit";

            if (msg.HasRequiresTenant)
            {
                sb.AppendLine($"            // [RequiresTenant] on {msg.TypeFullName}");
                sb.AppendLine($"            TurboMediator.Enterprise.TurboMediatorBuilderExtensions.WithMultiTenancy<{msg.TypeFullName}, {responseType}>(builder);");
            }

            if (msg.HasAuthorize)
            {
                sb.AppendLine($"            // [Authorize] on {msg.TypeFullName}");
                sb.AppendLine($"            TurboMediator.Enterprise.TurboMediatorBuilderExtensions.WithAuthorization<{msg.TypeFullName}, {responseType}>(builder);");
            }

            if (msg.HasTransactional)
            {
                sb.AppendLine($"            // [Transactional] on {msg.TypeFullName}");
                sb.AppendLine($"            TurboMediator.Persistence.TurboMediatorBuilderExtensions.WithTransaction<{msg.TypeFullName}, {responseType}>(builder);");
            }

            if (msg.HasAuditable)
            {
                sb.AppendLine($"            // [Auditable] on {msg.TypeFullName}");
                sb.AppendLine($"            TurboMediator.Persistence.TurboMediatorBuilderExtensions.WithAudit<{msg.TypeFullName}, {responseType}>(builder);");
            }

            if (msg.HasWithOutbox)
            {
                sb.AppendLine($"            // [WithOutbox] on {msg.TypeFullName}");
                sb.AppendLine($"            builder.Services.AddScoped<INotificationHandler<{msg.TypeFullName}>, TurboMediator.Persistence.Outbox.OutboxBehavior<{msg.TypeFullName}>>();");
            }
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
    }

    private static void GenerateConfigureRecurringJobs(StringBuilder sb, ImmutableArray<HandlerInfo> handlers)
    {
        var recurringHandlers = handlers
            .Where(h => !h.IsAbstract && h.RecurringJobId != null && h.RecurringJobCronExpression != null)
            .ToList();

        if (recurringHandlers.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Auto-registers recurring jobs discovered from [RecurringJob] attributes at compile time.");
        sb.AppendLine("        /// Zero reflection — all dispatch entries are generated as typed lambdas.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// Usage: scheduling.ConfigureRecurringJobsFromAttributes();");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        public static TurboMediator.Scheduling.DependencyInjection.SchedulingBuilder ConfigureRecurringJobsFromAttributes(");
        sb.AppendLine("            this TurboMediator.Scheduling.DependencyInjection.SchedulingBuilder builder)");
        sb.AppendLine("        {");

        foreach (var handler in recurringHandlers)
        {
            var commandType = handler.MessageTypeFullName;
            var responseType = handler.ResponseTypeFullName ?? "TurboMediator.Unit";
            var jobId = handler.RecurringJobId;
            var cron = handler.RecurringJobCronExpression;

            sb.AppendLine($"            // [RecurringJob(\"{jobId}\", \"{cron}\")] on {handler.HandlerTypeFullName}");

            if (handler.ResponseTypeFullName != null && handler.ResponseTypeFullName != "TurboMediator.Unit")
            {
                sb.AppendLine($"            builder.AddRecurringJob<{commandType}, {responseType}>(\"{jobId}\")");
            }
            else
            {
                sb.AppendLine($"            builder.AddRecurringJob<{commandType}>(\"{jobId}\")");
            }

            sb.AppendLine($"                .WithCron(\"{cron}\")");
            sb.AppendLine($"                .WithData(() => new {commandType}());");
            sb.AppendLine();
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
    }

    private static string GetHandlerInterface(HandlerInfo handler)
    {
        var hasResponse = handler.ResponseTypeFullName != null;

        return (handler.Kind, handler.IsStreaming, hasResponse) switch
        {
            (HandlerKind.Request, false, true) => $"IRequestHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            (HandlerKind.Request, false, false) => $"IRequestHandler<{handler.MessageTypeFullName}>",
            (HandlerKind.Command, false, true) => $"ICommandHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            (HandlerKind.Command, false, false) => $"ICommandHandler<{handler.MessageTypeFullName}>",
            (HandlerKind.Query, false, _) => $"IQueryHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            (HandlerKind.Notification, false, _) => $"INotificationHandler<{handler.MessageTypeFullName}>",
            (HandlerKind.Request, true, _) => $"IStreamRequestHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            (HandlerKind.Command, true, _) => $"IStreamCommandHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            (HandlerKind.Query, true, _) => $"IStreamQueryHandler<{handler.MessageTypeFullName}, {handler.ResponseTypeFullName}>",
            _ => throw new InvalidOperationException($"Unknown handler kind: {handler.Kind}")
        };
    }
}
