using System;

namespace TurboMediator.Caching;

/// <summary>
/// Options for configuring caching behavior.
/// </summary>
public class CachingBehaviorOptions
{
    /// <summary>
    /// Default cache duration applied when <see cref="CacheableAttribute.DurationSeconds"/> is not specified (0).
    /// Defaults to 5 minutes.
    /// </summary>
    public TimeSpan DefaultDuration { get; set; } = TimeSpan.FromMinutes(5);

    /// <summary>
    /// Global key prefix prepended to all cache keys generated by the caching behavior.
    /// Useful for namespace isolation in shared cache stores.
    /// Defaults to <c>null</c> (no global prefix).
    /// </summary>
    public string? GlobalKeyPrefix { get; set; }

    /// <summary>
    /// When <c>true</c>, sliding expiration is used by default when the <see cref="CacheableAttribute"/>
    /// does not explicitly set <see cref="CacheableAttribute.UseSlidingExpiration"/>.
    /// Defaults to <c>false</c> (absolute expiration).
    /// </summary>
    public bool DefaultUseSlidingExpiration { get; set; }
}
